### ISSUE TITLE
"Base" option stopped working

### ISSUE THREAD

**Issue by andreynering** [UnnoTed/fileb0x#9] opened 2017-03-20 19:56 UTC
Hi,

Seems that https://github.com/UnnoTed/fileb0x/commit/5494112a4d3e8629069278b3b0125960cd699c8d changes the behavior of `base`.

I have something like this:

```yml
custom:
  - files:
    - "public/js"
    - "public/css"
    base: "public/"
```

Before that commit, I could serve files as `/js/...` and `/css/...` instead of `/public/js/`. But now `public/` is not being removed from the path anymore.

Thanks for this awesome lib.

**Comment by UnnoTed** [comment] 2017-03-20 20:26
Hi, I couldn't reproduce.

Take a look at:
https://github.com/UnnoTed/fileb0x_issue9

**Comment by andreynering** [comment] 2017-03-21 11:14
Hmm...

I yesterday night tried this repo on Linux and it worked fine.

But I now tried on Windows and the problem happens.

See https://github.com/andreynering/fileb0x_issue9/commit/9ad872bdd6a9bf10dbbd9181203cd6328eca6dd1

**Comment by andreynering** [comment] 2017-03-21 11:34
Fix here: https://github.com/UnnoTed/fileb0x/pull/10

**Comment by UnnoTed** [comment] 2017-03-21 12:10
Merged, thanks!

**Closed by UnnoTed** 2017-03-21 12:10 UTC
